### ISSUE TITLE
Undefined symbol "libconfig::Config::lookupValue(char const*, std::basic_string...)" when libconfig compiled with clang and the code with g++

### ISSUE THREAD

**Issue by ibc** [hyperrealm/libconfig#10]
I've installed libconfig in OSX via `brew install libconfig` so it gets compiled with clang. Then I include `<libconfig.h++>` in my C++ project and link with `-lconfig++`.

If I compile my project with clang++ there is no problem, but if I compile it with g++ (4.8 or 4.9) I get this error:

```
Undefined symbols for architecture x86_64:
  "libconfig::Config::lookupValue(char const*, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const", referenced from:
      MyProject::ReadConfigFile()      in ccquVmsS.o
ld: symbol(s) not found for architecture x86_64
```

This is the usage of `lookupValue` within my code:

```
libconfig::Config* config = new libconfig::Config();
[...]
std::string str_value;
config->lookupValue("logLevel", str_value);
```

Taking a look into `libconfig++.h` it seems that the inline methods receiving a string (or char*) as second argument are causing this problem.

**Comment by louis-xu-ustc** [comment]
Also, the exact same issue happens to me. Any ideas to fix it?

**Comment by ibc** [comment]
As told above:

>  Same compiler must be used for bot libconfig and our custom code.
