### ISSUE TITLE
DLL project

### ISSUE THREAD

**Issue by AlexFundorin** [hyperrealm/libconfig#110]
How do I properly use this library in DLL project?
I'm writing an extension DLL plugin and want to use libconfig to create, read and write configuration files.
The problem is that as soon as i write 
Config cfg; or libconfig::Config cfg;
and then try to build the library, I get the following two errors in VS2017:
```
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl libconfig::Config::Config(void)" (__imp_??0Config@libconfig@@QEAA@XZ) referenced in function "private: void __cdecl SL::CmdFx(void)" (?CmdFx@SL@@AEAAXXZ)	sl	D:\cpp\Visual Studio\VisualStudio2015\sl.obj	1	

Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: virtual __cdecl libconfig::Config::~Config(void)" (__imp_??1Config@libconfig@@UEAA@XZ) referenced in function "private: void __cdecl SL::CmdFx(void)" (?CmdFx@SL@@AEAAXXZ)	sl	D:\cpp\Visual Studio\VisualStudio2015\sl.obj	1	
```

and this warning:
```
Warning	C4275	non dll-interface class 'std::exception' used as base for dll-interface class 'libconfig::ConfigException'	sl	d:\cpp\Library\libconfig\libconfig.h++	51	
```
How do I fix this and is it even possible to use libconfig with DLLs, by simply adding #include "../Library/libconfig/libconfig.h++" and using namespace libconfig; into the main cpp file?

**Comment by ttuti** [comment]
Did you ever find a solution? Struggling with the same problem even after adding the .lib files to the linker.

**Comment by hyperrealm** [comment]
I have no idea why this wouldn't work for you.

All the example programs under examples/ are linked to the DLLs by the libconfig Visual Studio project. Do those not build for you either?

**Comment by kyranf** [comment]
I have the same issue, it's super frustrating. I can't get visual studio to link it properly, I've got the directory paths right, i've built the library with the examples and solutions without any issue, 

If I do #include <libconfig.h++>  and use a few functions,  set the include directories and linker directories as needed, add libconfig++.lib to the linker dependencies, and attempt to compile I get all these warnings:
```
1>  Finished searching libraries
1>CameraModule.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class libconfig::Setting & __cdecl libconfig::Config::getRoot(void)const " (__imp_?getRoot@Config@libconfig@@QEBAAEAVSetting@2@XZ)
1>CameraModule.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: bool __cdecl libconfig::Setting::lookupValue(char const *,bool &)const " (__imp_?lookupValue@Setting@libconfig@@QEBA_NPEBDAEA_N@Z)
1>CameraModule.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: bool __cdecl libconfig::Setting::lookupValue(char const *,int &)const " (__imp_?lookupValue@Setting@libconfig@@QEBA_NPEBDAEAH@Z)
1>CameraModule.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class libconfig::Setting & __cdecl libconfig::Setting::operator[](char const *)const " (__imp_??ASetting@libconfig@@QEBAAEAV01@PEBD@Z)
1>AppConfig.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl libconfig::Config::readFile(char const *)" (__imp_?readFile@Config@libconfig@@QEAAXPEBD@Z)
1>AppConfig.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl libconfig::Config::~Config(void)" (__imp_??1Config@libconfig@@UEAA@XZ)
1>AppConfig.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl libconfig::Config::Config(void)" (__imp_??0Config@libconfig@@QEAA@XZ)
1>AppConfig.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: bool __cdecl libconfig::Setting::lookupValue(char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)const " (__imp_?lookupValue@Setting@libconfig@@QEBA_NPEBDAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>AppConfig.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: char const * __cdecl libconfig::ParseException::getError(void)const " (__imp_?getError@ParseException@libconfig@@QEBAPEBDXZ)
1>AppConfig.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: int __cdecl libconfig::ParseException::getLine(void)const " (__imp_?getLine@ParseException@libconfig@@QEBAHXZ)
1>AppConfig.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: char const * __cdecl libconfig::ParseException::getFile(void)const " (__imp_?getFile@ParseException@libconfig@@QEBAPEBDXZ)
1>D:\Projects\Mushrooms\Harvester\Harvester\x64\Release\Harvester.exe : fatal error LNK1120: 11 unresolved externals
```

it should have found it, in the directory:
```
    Searching ..\..\third-party\libconfig-1.7.2\Release\libconfig++.lib:
```

I can't even compile, so it's not like it can't link the .dll or anything. I will put the .dll in the executable directory if it's needed after, but why can't I even compile my project with libconfig used?

**Comment by DentonW** [comment]
This is obviously an old issue, but in case someone runs across the same error like I just did, it's an issue with the wrong export attributes via libconfig.h or libconfig.h++. Issue #55 addresses this: [https://github.com/hyperrealm/libconfig/issues/55](https://github.com/hyperrealm/libconfig/issues/55).

**Comment by kyranf** [comment]
As an additional note to my comment I posted, I found out that I was doing 32bit and 64bit libraries mixed up :(

I have it working now.

**Comment by keineahnung2345** [comment]
@kyranf So many thanks! I've installed libconfig through `vcpkg`, but by default it installed the `x86-windows` version. After I installed the x64 version through `vcpkg install libconfig:x64-windows`, my project can run successully!
