### ISSUE TITLE
Setting names starting with a number

### ISSUE THREAD

**Issue by lminiero** [hyperrealm/libconfig#111]
The documentation states:

    All names are case-sensitive. They may consist only of alphanumeric
    characters, dashes (‘-’), underscores (‘_’), and asterisks (‘*’), and
    must begin with a letter or asterisk.

Any reason why they MUST begin with letter or asterisk, and not a number, let's say? I'm trying to use libconfig for my project, as I really like the format and the API is quite neat, but this constraint is a bit of a bummer, as I currently have many objects whose key name are numbers, and they cause parsing to just fail. I know I can prefix them with a letter as a hack to get it working, but I'd rather not do that if possible, as I'm keeping our old configuration format as a fallback for backwards compatibility, and use a wrapper API to transparently access one or the other depending on the format in use. Prefixing is not something I can do within the wrapper itself, as these setting names only make sense to dynamic modules that use the wrapper.

Thanks for any feedback oyu may have for me.

**Comment by hyperrealm** [comment]
Basically it's the same reasoning as for disallowing symbols in programming languages from having names that start with a number (or that consist of numbers). It's to prevent symbol names from being misinterpreted as numeric constants. If you allowed it, you could have absurd things in the configuration like "0 = 1" or "1e5 = 2222"
