### ISSUE TITLE
./configure error

### ISSUE THREAD

**Issue by dkuo123** [hyperrealm/libconfig#113]
I just git clone the master and try to build on Centos using autoconf 2.69
[dguo@centos-dev libconfig]$ ./configure 
...
hecking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
./configure: line 3577: syntax error near unexpected token `ac_ext=c'
./configure: line 3577: `ac_ext=c'

so my cmake couldn't run.
can you help?
thanks,
david

**Comment by hyperrealm** [comment]
No way to know what's wrong without knowing how you generated the configure script. Did you try the source tarball instead? Does the configure script included therein work?

**Comment by hyperrealm** [comment]
Did you run 'autoreconf' first, as explained in the INSTALL file?

**Comment by MarkRijckenberg** [comment]
I encountered the same error "syntax error near unexpected token ac_ext=c' ./configure: line 3577: ac_ext=c'" when compiling a different program (eid-mw) from source code in Kubuntu 19.10. I had three packages installed: gcc-7-base gcc-8-base gcc-9-base
The solution for me was to uninstall the conflicting packages gcc-7-base and gcc-8-base and only keep gcc-9-base installed...
