### ISSUE TITLE
I am trying to static link liblibconfig++.a 

### ISSUE THREAD

**Issue by cempayzin** [hyperrealm/libconfig#123]
I am not sure I understand static link issues. I have downloaded and compiled libconfig as static library. However if I tried to link C version of lib linker finds all functions. However if I tried linking C++ version of lib, linker failes to located multiple functions. I extracted object files from compiled libconfig.a and libconfig++.a I did not see requiredfunctions are added to C++ version of the lib. 

I can explain more details if needed. I compile on Ubuntu Server LTS 18.x 

Cem

**Comment by hyperrealm** [comment]
Hard to say without knowing how you're building this. Check the output of 'nm libconfig++.a' and see if the problematic symbols are there (should have a 'T' next to them), for example:

0000000000001030 T config_init
