### ISSUE TITLE
can't static link libconfig++_d.lib

### ISSUE THREAD

**Issue by VeblenXSYK** [hyperrealm/libconfig#125]
I use libconfig_vs2017.sln build out static debug lib, but I  build error when static link it, The error message is as follows
`LNK2019	 unresolved external symbol "__declspec(dllimport) public: bool __thiscall libconfig::Setting::lookupValue`
Thanks in advance for your feedback！！！

**Comment by hyperrealm** [comment]
You need to #define LIBCONFIG_STATIC before you #include the libconfig header.

**Comment by VeblenXSYK** [comment]
Y

> You need to #define LIBCONFIG_STATIC before you #include the libconfig header.

Yes, I do it, but It's the same problem.
`#pragma once
#define WIN32_LEAN_AND_MEAN             // 从 Windows 头中排除极少使用的资料
#include <windows.h>
#include <tchar.h> 

// DM
#include "DmMainOutput.h"

// PSCore
#include "PSExport.h"

// libconfig
**#define LIBCONFIG_STATIC**
#include "libconfig.h++"

// lib
#ifdef _DEBUG
#pragma comment(lib,"DmMain_d.lib")
#pragma comment(lib,"PsDump_d.lib")
#pragma comment(lib,"Jpeg_d.lib")
#pragma comment(lib,"PSCore_d.lib")
**#pragma comment(lib,"libconfig++_d.lib")**
`
