### ISSUE TITLE
Linker error with "bool lookupValue(const char *name, std::string &value) const"

### ISSUE THREAD

**Issue by r4nd0m6uy** [hyperrealm/libconfig#126]
Hi libconfig maintainers!

I tried to compile an old personal project and I have a compiler error with the latest libconfig version:

> libcgclib.a(Options.cpp.o): In function `cgc::Options::parseOptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
Options.cpp:(.text+0xd8): undefined reference to `libconfig::Config::lookupValue(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/cgc.dir/build.make:85: src/cgc] Error 1
make[1]: *** [CMakeFiles/Makefile2:93: src/CMakeFiles/cgc.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

The following snippet works:
```cpp
int Options::parseOptions(const std::string file)
{
  libconfig::Config cfg;
  int intOption;

  /* omitted */

  if(cfg.lookupValue("uci.threads", intOption))
    /* omitted */

  return 0;
}
```

But this doesn't
```cpp
int Options::parseOptions(const std::string file)
{
  libconfig::Config cfg;
  std::string stringOption;
  int intOption;

  /* omitted */

  // HAI HAI HAI!!!
  if(cfg.lookupValue("uci.path", stringOption))
    /* omitted */

  if(cfg.lookupValue("uci.threads", intOption))
    /* omitted */

  return 0;
}
```

I'm pretty sure it should work, this is defined in the libconfig.h++:
```cpp
class LIBCONFIGXX_API Config
{
  public:
  /* ... */
  bool lookupValue(const char *path, std::string &value) const;
```

I know it was working with and older version, as it was specified in the CmakeLists.txt:
```cmake
pkg_search_module(LIBCONFIG REQUIRED libconfig++>=1.4.9)
```

Running [Void Linux](https://voidlinux.org/) with gcc:
> $ gcc --version
gcc (GCC) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Or did I miss something?

**Comment by hyperrealm** [comment]
Hi, I was not able to reproduce this. I added the following snippet of code in examples/c++/example1.cpp:55

  string tmp;
  cfg.lookupValue("name", tmp);
  std::cout << "name: " << tmp << std::endl;

It compiles fine and the output is as expected:

name: Books, Movies & More

**Comment by ilyapopov** [comment]
What can happen here is if the library was compiled with C++03, and the application is compiled with C++11 or later, there can incompatibility. GCC had broken string ABI between C++03 and C++11 (they were using COW strings before). Notice a string is called `std::__cxx11::basic_string` in the error message, which means "new ABI string". To see what exactly is defined in the library, run `nm -C libconfig++.a`. It will probably define the function for string without `__cxx11` bit.

**Comment by r4nd0m6uy** [comment]
So I tried to narrown down the problem, build the vanilla library manually and could successfully compile a working application with the latest stable and dev version (1.7.2 / 0e7bf4d156).

I guess the problem is not from you but thanks to @ilyapopov, I've already had similar issues on my system with clang++/g++ or since gcc upgraded few time since then, some mangling changes or whatever could be the issue.

*Conclusion:* I think this bug can be closed and will check with my distro developpers (void linux) if there is something that can be done here! 

Thanks for considering my issue!

**Comment by r4nd0m6uy** [comment]
Just to confirm @ilyapopov comment, the problem was related to the ABI compatibility, guys from my distro recompile the package and now it works!
