### ISSUE TITLE
throw specifications removed from C++ language

### ISSUE THREAD

**Issue by jwmelto** [hyperrealm/libconfig#129]
I cannot use this library because C++ removed throw specification from the language as of C++17.

Throw specs were never terribly useful and widely misunderstood. Unlike the Java counterpart, they do not provide any compilation help, but instead cause runtime failures if an unexpected exception is encountered. 

Since the best they can do is hurt, and they were deprecated in C++11 and completely removed in C++17, how about removing the throw specs from the C++ language binding?

**Comment by hyperrealm** [comment]
Sure. Can you upload a patch?

**Comment by hyperrealm** [comment]
fixed in 18193744f841a2537073a43b193ef7120089e9a7
