### ISSUE TITLE
[QUESTION]  questions about invalid names

### ISSUE THREAD

**Issue by nezen** [hyperrealm/libconfig#133]
I find that there is a constraint that key names can not start with digital numbers.
I wonder if I can remove the constraints?

I already made it to write invalid names by changing the function '__config_validate_name'.
But still I've no idea how to make it work when reading a conf file with invalid names.
It's very nice of you if you can provide some clues for me. Thanks a lot !

**Comment by hyperrealm** [comment]
You'll have to change the regular expression on line 59 of scanner.l

I don't recommend this however, as you may end up with an ambiguous grammar. For example a token like "1e2" could be interpreted as both a name and a floating point number.

**Comment by nezen** [comment]
That's very helpful, thanks!
