### ISSUE TITLE
unresolved external symbol snprintf referenced in function format_double

### ISSUE THREAD

**Issue by sgolubev33** [hyperrealm/libconfig#139]
Hi!
When compiling libconfig using MS Visual Studio 2013 (using libconfig_vs2017.sln) receiving linker error:
util.obj : error LNK2019: unresolved external symbol snprintf referenced in function format_double

I've found re definition in wincompat.h
#if _MSC_VER < 1800
#define snprintf  _snprintf
#endif

For MS Visual Studio 2013 _MSC_VER eaquals 1800.

I've fixed this redefinition like this:
#if _MSC_VER <= 1800
#define snprintf  _snprintf
#endif

Please, include this change to main project

**Comment by hyperrealm** [comment]
Fixed in 52b002312a9c334676126fe0ec81a5cb5011dd6f
