### ISSUE TITLE
The local function in the libconfig package has the same name call error.

### ISSUE THREAD

**Issue by PCwangPY** [hyperrealm/libconfig#140]
The internal function of strbuf_append_string defined in libconfig has the same name as other open source libraries. Once the program calls this function, it will not call this internal function, it will call another existing function with the same name.
Suggested solutions:
a) The reason for finding the duplicate name is because the same name caused by the last modified function name appears, then you can modify the function name again, you can add __ in front of the function name to distinguish (__strbuf_append_string).
b) You can use the gcc extended attribute __attribute__ ((visibility("hidden")))
Concrete implementation: the declaration location of this function of the same name is in strbuf.h in lib
/* ------------------------------------------------ ----------------------------
   Libconfig - A library for processing structured configuration files
   Copyright (C) 2005-2018 Mark A Lindner

   This file is part of libconfig.

   This library is free software; you can redistribute it and/or
   Modify it under the terms of the GNU Lesser General Public License
   As published by the Free Software Foundation; either version 2.1 of
   The License, or (at your option) any later version.

   This library is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
   Lesser General Public License for more details.

   You should have a copy of the GNU Library General Public
   License along with this library; if not, see
   <http://www.gnu.org/licenses/>.
   -------------------------------------------------- --------------------------
*/

#ifndef __libconfig_strbuf_h
#define __libconfig_strbuf_h

#include <string.h>
#include <sys/types.h>

Typedef struct
{
  Char *string;
  Size_t length;
  Size_t capacity;
} strbuf_t;

__attribute__ ((visibility("hidden"))) void strbuf_append_string(strbuf_t *buf, const char *s);

Void strbuf_append_char(strbuf_t *buf, char c);

Char *strbuf_release(strbuf_t *buf);

#endif /* __libconfig_strbuf_h */

The above are the problems I found and the solutions I have solved.

**Comment by hyperrealm** [comment]
Fixed in 8acc6201dd195f2e3ea4453563922549b4b6aec4
