### ISSUE TITLE
After ./configure, make gives following errors

### ISSUE THREAD

**Issue by gaurivn** [hyperrealm/libconfig#145]
gauri@gauri-HP-Laptop-15-bs1xx:~/Downloads/libconfig-1.7.2$ make
make  all-recursive
make[1]: Entering directory '/home/gauri/Downloads/libconfig-1.7.2'
Making all in lib
make[2]: Entering directory '/home/gauri/Downloads/libconfig-1.7.2/lib'
make  all-am
make[3]: Entering directory '/home/gauri/Downloads/libconfig-1.7.2/lib'
  CXXLD    libconfig++.la
/usr/bin/ld: .libs/libconfig___la-libconfigcpp.o: relocation R_X86_64_PC32 against symbol `_ZN9libconfig15ConfigExceptionC2Ev' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:542: recipe for target 'libconfig++.la' failed
make[3]: *** [libconfig++.la] Error 1
make[3]: Leaving directory '/home/gauri/Downloads/libconfig-1.7.2/lib'
Makefile:461: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/gauri/Downloads/libconfig-1.7.2/lib'
Makefile:446: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/gauri/Downloads/libconfig-1.7.2'
Makefile:376: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gaurivn** [comment]
Solved

**Comment by motognere** [comment]
Hi,

I came across with the same issue. Could you please share how you get it solved?
The issue doesn't occur if building libconfig in normal Ubuntu system, except when I'm trying to build and install it in a docker container.
I suppose there probably some dependency missing in the ubuntu in docker container?
Look forward to any help.

Thanks.
