### ISSUE TITLE
'configure' file is missing

### ISSUE THREAD

**Issue by FrankSansC** [hyperrealm/libconfig#15]
Hi ! I've just clone your repository and noticed that the 'configure' file is missing. Did you changed the way to compile your library ?

Thanks in advance for your help.

**Comment by Yotamki** [comment]
+1

**Comment by tpoechtrager** [comment]
Please read the `automake` manual...

`autoreconf -vfi`

**Comment by Yotamki** [comment]
Great - thanks for the help.

This should go to the README file though. The ./configure; make; make install cycle described there is insufficient.

**Comment by hyperrealm** [comment]
I've added the configure script to the repo.
