### ISSUE TITLE
why libconfig::Setting is private?

### ISSUE THREAD

**Issue by nickhuangxinyu** [hyperrealm/libconfig#159]
How should i do if i want to use libconfig::setting as function parameter?

**Comment by thomastrapp** [comment]
> How should i do if i want to use libconfig::setting as function parameter?

This works, for example:

```c++
#include <libconfig.h++>
#include <iostream>

void example(const libconfig::Setting& settings)
{
  std::string abc = settings.lookup("abc");
  std::cout << abc << "\n";
}

int main()
{
  libconfig::Config config;
  config.readString("abc = \"abc\";");

  example(config.getRoot());

  return 0;
}
```

**Comment by nickhuangxinyu** [comment]
> > How should i do if i want to use libconfig::setting as function parameter?
> 
> This works, for example:
> 
> ```c++
> #include <libconfig.h++>
> #include <iostream>
> 
> void example(const libconfig::Setting& settings)
> {
>   std::string abc = settings.lookup("abc");
>   std::cout << abc << "\n";
> }
> 
> int main()
> {
>   libconfig::Config config;
>   config.readString("abc = \"abc\";");
> 
>   example(config.getRoot());
> 
>   return 0;
> }
> ```

Can I save setting in a class as a member variable, waiting to use it in the future? like:
Class A {
  A(libconfig::Setting s) {

  }
private:
  libconfig::Setting a;
}

int main() {
   libconfig::Config config;
   config.readString("abc = \"abc\";");
   A(config.lookup("abc"));
}

I dont think this works

Can you offer some suggestions, i am bothered by this for a long time

**Comment by thomastrapp** [comment]
> A(libconfig::Setting s) : a(s)

Unfortunately, that doesn't work, because `libconfig::Setting` can not be copied (by design).

> Can you offer some suggestions

It depends on your use case. Personally, I think a good approach is to never pass a `libconfig::Setting` when possible, but the setting's value instead. It makes for clearer code.

```c++
class Connection
{
public:
  Connection(std::string hostname, int port);
}
// ...
std::string hostname = config.lookup("hostname");
int port = config.lookup("port");
Connection connection(hostname, port);
```

**Comment by nickhuangxinyu** [comment]
@thomastrapp thx a lot!
