### ISSUE TITLE
@include should be smarter when considering pathes

### ISSUE THREAD

**Issue by coldtobi** [hyperrealm/libconfig#16]
Hi hyperrealm,

When using @include to get nested configuration files, it can be somehow cumbersome to get it right:
especially when the user wants to use relative paths (and/or absoute paths). Currently the behaviour
of libconfig is also dependend on the current working directory.

One can set a include dir, but that can also confuses libconfig as it will always use that path,
regardless if an absolute or relative path is given.*

It would be great if libconfig could be a little smarter when parsing includes:
-> when the path of the include starts with "/" the set include dir should be ignored and an absoute path assumed
-> maybe, additionally, if the path starts with "./" consider this a relative path to the currently parsed configuration file? 

Thanks!

*for example:

with include-dir set to /etc/foo/ 
 
@include bar.conf
will include /etc/foo/bar.conf

but 
@include /etc/bar.conf
will (try to) include /etc/foo//etc/bar.conf 

(this report applies to 1.4.9; I did not check against trunk but a brief check of the commit messages looks like that this feature request is still valid. If not, sorry for the noise)

Kudos for your fine library!

--
tobi

**Comment by hyperrealm** [comment]
Thanks for reporting this. I'll try to get a fix in as soon as I have a chance.
