### ISSUE TITLE
c config not working in libconfig_1.7.2

### ISSUE THREAD

**Issue by Yordanost** [hyperrealm/libconfig#160]
Hello,

We had been using libconfig in our project for a while, running version 1.5. Recently, we upgraded to version 1.7.2, as we had faced some memory related problem in the previous version. 

However, after the upgrade, the c config is not working anymore. Below is a snapshot of the code where the error is seen.
             
             config_init(&cfg);

		/* Read the file. If there is an error, report it and exit. */
		if(! config_read_file(&cfg, filename))
		{
			fprintf(stderr, "Error reading file %s:%d - %s\n", filename, config_error_line(&cfg), config_error_text(&cfg));
			config_destroy(&cfg);
			return 1;
		}
Is there another way to initialize the config? 
The examples available seem to have the same setting as ours as well. Would be great if anyone can share with us a working example for version 1.7.2

Thanks for your help in advance!
Yordanos

**Comment by thomastrapp** [comment]
> However, after the upgrade, the c config is not working anymore

In what way is it not working?

> Below is a snapshot of the code where the error is seen
> [...]

Looks fine to me.
https://www.hyperrealm.com/libconfig/libconfig_manual.html#The-C-API

**Comment by Yordanost** [comment]
Hi, thanks for your quick response!

The error message 
             Error reading file.... (shown in the code above) is displayed and the config file is not read

**Comment by thomastrapp** [comment]
Can you paste the error message?

> Is there another way to initialize the config?

There are some options:
https://hyperrealm.github.io/libconfig/libconfig_manual.html#index-config_005fset_005foptions

**Comment by Yordanost** [comment]
Error reading file (null):355281737 - (null)

The filename and cfg are initialized as

const char *filename=configFileName;
config_t cfg;

**Comment by thomastrapp** [comment]
> Error reading file (null):355281737 - (null)

That doesn't look good :-)

Your `const char * filename` pointer is `NULL`.
