### ISSUE TITLE
Can you let me know why libconfig forbid copy?

### ISSUE THREAD

**Issue by nickhuangxinyu** [hyperrealm/libconfig#163]
libconfig is a great tool, but no copy design cause a lot of inconvience for me, for example:

if i have a config that record all stock's config(like: fee_rate, stock_price ....)

I write all stocks' config in one config file

I want to build a worker to save this into a map (key is stock name, value is libconfig::Setting for this stock), it will fail, because "=" is private

I think libconfig is a masterpiece, So, what is the purpose to make = and contructor private?(forbid to copy)

**Comment by hyperrealm** [comment]
This is because a copy could potentially be an expensive operation and it may not be immediately obvious to a developer that assigning one setting to another will perform a deep copy.

There is a function in contrib/copy_setting.c that will do a deep copy.

**Comment by keineahnung2345** [comment]
It seems the deep copy function is only for C, not for C++?
