### ISSUE TITLE
Semicolon mandatory while reading cfg.readFile(filename); - for validation

### ISSUE THREAD

**Issue by gaurav360** [hyperrealm/libconfig#166]
How to make semicolon mandatory while reading CFG file. Idea is to validate if missing semicolon is present or not.

**Comment by hyperrealm** [comment]
Change this production in the grammar.y file:

setting_terminator:
    /* empty */
  | TOK_SEMICOLON
  | TOK_COMMA
  ;

to:

setting_terminator:
    TOK_SEMICOLON
  | TOK_COMMA
  ;
