### ISSUE TITLE
miss configure

### ISSUE THREAD

**Issue by xiaonaiquan** [hyperrealm/libconfig#183]
There is no configure file in the project,How do you build a statically linked library?

**Comment by tkrypton** [comment]
That's covered in the INSTALL file:

Installation from Cloned Git Repository
=======================================

If you obtained the package by cloning the git repository, there are some
additional steps required to build the package, as the generated 'configure'
script and other supporting build files are not included in the repository.
...

In short: use autoreconf after you've installed the usual set of autotools mentioned in the INSTALL file.

HTH,
Uli

**Comment by xiaonaiquan** [comment]
> That's covered in the INSTALL file:
> 
> # Installation from Cloned Git Repository
> If you obtained the package by cloning the git repository, there are some
> additional steps required to build the package, as the generated 'configure'
> script and other supporting build files are not included in the repository.
> ...
> 
> In short: use autoreconf after you've installed the usual set of autotools mentioned in the INSTALL file.
> 
> HTH,
> Uli

thank you ,i will try again!
