### ISSUE TITLE
fatal run-time error using "config_read_file" function

### ISSUE THREAD

**Issue by ramiral92500** [hyperrealm/libconfig#189]
Hello,
I'm starting to use  different functions from this library.
I'm using LabWindows CVI 20 but the problem should not be linked with this tools.
My projet is linked to the libconfig library using the function "GetProcAddress"

The function called "config_read_file" works perfectly, but not the function called "config_read" 

The function called "config_read " returns a fatal runtime error:

- I correctly open a file strem using "fopen" (i verify that I can read inside the file using the function "fgets").
- the structure config_t is correctly initialized using the function called [config_init]

![fatalerror](https://user-images.githubusercontent.com/81693605/113154365-3df19b00-9238-11eb-84b4-bc687315b08c.jpg)

**Comment by hyperrealm** [comment]
I unfortunately have no way to debug this.

**Comment by hyperrealm** [comment]
I am closing this because it's not actionable. Since config_read_file() internally calls config_read(), it's unlikely that there's a problem with config_read(). I've added a unit test to exercise config_read() and on Linux at least, I do not see any issues with it.
