### ISSUE TITLE
libconfig.c::config_read_file crashes on wrong file path

### ISSUE THREAD

**Issue by Yotamki** [hyperrealm/libconfig#19]
fclose(stream) will not work on NULL pointers.

I changed to:
  if(!ok)
  {
    if (stream != NULL)
    {
      fclose(stream);
    }
    config->error_text = __io_error;
    config->error_type = CONFIG_ERR_FILE_IO;
    return(CONFIG_FALSE);
  }

**Comment by hyperrealm** [comment]
Thanks, I've merged the fix.
