### ISSUE TITLE
how to use libconfig to read several config files in one object?

### ISSUE THREAD

**Issue by nickhuangxinyu** [hyperrealm/libconfig#197]
Assume I have a `libconfig::config` object, can i `readFile` for several times like this:

```
libconfig::Config cfg;
cfg.readFiles("./a.cfg");
cfg.readFiles("./b.cfg");
```
and what will happen if a.cfg and b.cfg have same key?

If this doesnt work, is there any methods can let me merge two config files' setting into one object?

**Comment by thomastrapp** [comment]
> can i readFile for several times like this

`readFiles` clears the config ([libconfig.c](https://github.com/hyperrealm/libconfig/blob/master/lib/libconfig.c#L533-L541)): The values from "a.cfg" will be discarded, when calling `readFiles` a second time.

You can use [@include](https://hyperrealm.github.io/libconfig/libconfig_manual.html#Include-Directives):
> A configuration file may “include” the contents of other files using an include directive.
> This directive has the effect of inlining the contents of the named file(s) at the point of inclusion. 

See also the option [Config::OptionAllowOverrides](https://hyperrealm.github.io/libconfig/libconfig_manual.html#index-setOptions-on-Config), which allows you to include configuration files that override already existing settings.

**Comment by nickhuangxinyu** [comment]
@thomastrapp  thanks very much.

@inlcude is cool, can you teach me about, where can i find all @ wildcards setting (for example: @include, @...) for libconfig?
