### ISSUE TITLE
serialize config into a string

### ISSUE THREAD

**Issue by keineahnung2345** [hyperrealm/libconfig#199]
I'd like to write the config into a encrypted file, so following is what I want to achieve: 
1. serialize config into a string(stuck here)
2. encrypt the string
3. write the encrypted string into a file

I've found that there is a `int config_read_string(config_t *config, const char *str)` function in `lib/libconfigc`, but I can't find corresponding `config_write_string` function, so how to I serialize config into a string? Thanks.

**Comment by thomastrapp** [comment]
For Linux, it may be possible to use `config_write` with a `FILE *` obtained from [open_memstream](https://man7.org/linux/man-pages/man3/open_memstream.3.html) or [fmemopen](https://man7.org/linux/man-pages/man3/fmemopen.3.html).

Another solution is to encrypt only specific values and embed them as strings in the config. This way the data is encrypted before it is passed to `config_write`.

**Comment by keineahnung2345** [comment]
After some search, I've found `fmemopen` analog on Windows, and I've put my revision [here](https://github.com/keineahnung2345/cpp-code-snippets/blob/master/file_delete_on_close.c).
By using it with [file_read_write_concurrently.c](https://github.com/keineahnung2345/cpp-code-snippets/blob/master/file_read_write_concurrently.c), I can open that memory file, call `cfg.writeFile` on it, read from it and then close(also delete) it.
