### ISSUE TITLE
Missing Makefile.in for configure script?

### ISSUE THREAD

**Issue by l0ud** [hyperrealm/libconfig#20]
I can see there is a new configure script. However, while trying to use it, I'm getting error:
config.status: error: cannot find input file: `Makefile.in'

**Comment by borellim** [comment]
I confirm: I get the same error.

**Comment by tpoechtrager** [comment]
You can generate the missing files with `autoreconf -vfi`.

**Comment by borellim** [comment]
Thank you, that worked. But then it's a bit different from what's written in the INSTALL file. The problem is not the extra command, but the fact that autoconf, automake and libtool are required for compilation. Shouldn't this be clarified? Thanks.

**Comment by hyperrealm** [comment]
The INSTALL file directions are really meant for the source tarball that you can download from www.hyperrealm.com, which includes all the necessary files to build.

**Comment by borellim** [comment]
I see, thanks for the clarification. I had downloaded the tar.gz from the "releases" section on github, thinking that they would be equivalent. My bad.

I encountered another error during 'make', but I will make a new thread about it.

**Comment by snscltt** [comment]
But www.hyperrealm.com only provides insecure methods to obtain the source. No https, no checksums. Providing all necessary files to build right here or providing a secure download for said tarball would be much appreciated.

**Comment by hyperrealm** [comment]
I added all the .in files to the repo.
