### ISSUE TITLE
Debian 11 version and build

### ISSUE THREAD

**Issue by lucapaganotti** [hyperrealm/libconfig#200]
Hi,

I recently upgraded my linux box from debian 10 to 11. I had installed libconfig and libconfig++ on debian 10, upgrading to debian 11 seemed fine until I tried to compile and build against libconfig.

The package distributed in debian 11 seems to be libconfig version 1.5.x .

Linking against it gives me strange errors:

`undefined reference to libconfig::Config::Config()`
`undefined reference to libconfig::Config::~Config()`

upon declaration of a Config object:

`libconfig::Config cfg;`

but the include files clearly states that constructor and virtual destructor of Config objects exist. The libraries were in place in 

/usr/lib/x86_64-linux-gnu/

I remove and purge the libconfig distribution packages and clone from github, build && install correctly the last version (1.7) but I get the same errors.

What am I missing?

**Comment by hyperrealm** [comment]
Closing due to lack of information.
