### ISSUE TITLE
How to enumerate keys for dict?

### ISSUE THREAD

**Issue by nickhuangxinyu** [hyperrealm/libconfig#201]
```
dict = {
 key1="a";
 key2="b";
};

```
can i enumerate keys for dict (it's key1 and key2)?

i know this can be implemented by:
```
dict = (
{
 key="key1";
 value="a"
},
{
 key="key2";
value="b";
}
);
```

but this seems be wired, can you add the enumerate method in next version?

**Comment by hyperrealm** [comment]
You can enumerate groups the same way you enumerate lists and arrays, using config_setting_length() and config_setting_get_elem().

**Comment by nickhuangxinyu** [comment]
can you provide a demo code?  thanks very much!! @hyperrealm

**Comment by hyperrealm** [comment]
const Setting &dict = cfg.lookup("dict");
for (int i = 0; i < dict.getLength(); ++i) {
  const Setting &child = dict[i];
  // child.getName() is the key 
}



examples/c++/example1.cpp has an example of exactly this
