### ISSUE TITLE
how to overwrite current config's setting?

### ISSUE THREAD

**Issue by nickhuangxinyu** [hyperrealm/libconfig#204]
For libconfig::Setting object, how to overwrite a setting?

For example, in my config:
a = 1;

how to overwrite a in my c++ code?

I think libconfig::Setting.add("a", libconfig::Setting::TypeInt) = 3, not work.

**Comment by hyperrealm** [comment]
Please refer to the [documentation](https://hyperrealm.com/libconfig/libconfig_manual.html). All of these things are covered in detail there.
