### ISSUE TITLE
Windows Build - _S_ISDIR unresolved

### ISSUE THREAD

**Issue by RobotCaleb** [hyperrealm/libconfig#21]
I am attempting to build libconfig using VS2013. After opening the provided .sln it goes through a conversion step to bring it up to 2013 format. That goes well enough.

The build of libconfig library fails as `<sys/stat.h>` on Windows doesn't contain a definition for `S_ISDIR` which is called in `libconfig.c` in `config_read_file()`.

I am able to coerce a build out of it by changing that line to `if (!(statbuf.st_mode & S_IFDIR) != 0)`
The examples all seem to work fine with this change.

**Comment by RobotCaleb** [comment]
`libconfig_tests` runs with two failures, which I assume have nothing to do with file reading.

Here's the output of libconfig_tests:
```
[TEST] ParsingAndFormatting
parsing testdata/input_0.cfg
parsing testdata/input_1.cfg
parsing testdata/input_2.cfg
parsing testdata/input_3.cfg
parsing testdata/input_4.cfg
parsing testdata/input_5.cfg
parsing testdata/input_6.cfg
[ OK ] ParsingAndFormatting
[TEST] ParseInvalidFiles
[ OK ] ParseInvalidFiles
[TEST] ParseInvalidStrings
[ OK ] ParseInvalidStrings
[TEST] BigInt1
[ OK ] BigInt1
[TEST] BigInt2
[ OK ] BigInt2
[TEST] BigInt3
[ OK ] BigInt3
[TEST] BigInt4
[ OK ] BigInt4
[TEST] BigInt5
[ OK ] BigInt5
[TEST] BigInt6
tests.c:377: failed assert: (llval) [-2147483648] == (-2147483648) [2147483648]
[FAIL] BigInt6
[TEST] BigInt7
tests.c:407: failed assert: (llval) [-2147483649] == (-2147483649) [2147483647]
[FAIL] BigInt7
*** FAILURES! ***
10 tests; 8 passed, 2 failed
```

**Comment by hyperrealm** [comment]
I added a check in wincompat.h
