### ISSUE TITLE
x86 build instructions

### ISSUE THREAD

**Issue by OneParsec** [hyperrealm/libconfig#216]
How can I build libconfig to the win32(x86) platform, using 64-bit visual studio 2022?

**Comment by thomastrapp** [comment]
I don't use Visual Studio often.
Have you tried using [libconfig_vs2017.sln](https://github.com/hyperrealm/libconfig/blob/master/libconfig_vs2017.sln) and switching the target platform to win32?

**Comment by OneParsec** [comment]
Yeah, i tried, but it says this solution doesn't have this configuration.

**Comment by OneParsec** [comment]
I also tried add this configuration but I have error that this configuration was already created.
