### ISSUE TITLE
Setting::exists and Setting::lookup do not agree for some path strings

### ISSUE THREAD

**Issue by sgibbs-DSI** [hyperrealm/libconfig#220]
If a path to a scalar setting is expressed with `.[0]` at the end of the path, `Setting::exists` will return true, but `Setting::lookup` will throw `SettingNotFoundException`.

This appears to relate to the underlying calls:
- Setting::exists uses `config_setting_get_member`
- Setting::lookup uses `config_setting_lookup`

> Note:
> This issue does not occur with Config::exists and Config::lookup, which both use `config_lookup` method.

So, simple config file that contains only one key:
> parameter = 100

`config_setting_get_member(s, "parameter.[0]")` will return the setting for "parameter" rather than NULL

**Comment by hyperrealm** [comment]
There were various bugs here, which are fixed in 5ff6aecbdb7f85a8e7a2ea7fd63c03b4bdd42076
