### ISSUE TITLE
Cannot configure project

### ISSUE THREAD

**Issue by MKrbm** [hyperrealm/libconfig#228]
I pulled master branch updated recently and tried to configure my project.  However, I got errors.

```
[cmake] CMake Error at Release/_deps/libconfig-src/CMakeLists.txt:5 (file):
[cmake]   file STRINGS option REGEX value "^AC_INIT\([libconfig],[ 	]*[([0-9.]+)],.*"
[cmake]   could not be compiled.
[cmake] CMake Error at Release/_deps/libconfig-src/CMakeLists.txt:7 (string):
[cmake]   string sub-command REGEX, mode REPLACE failed to compile regex
[cmake]   "^AC_INIT\([libconfig],[ 	]*[([0-9.]+)],.*".
```

v1.7.3 works fine. Thank you.

**Comment by hyperrealm** [comment]
Yes, I tried to fix that, but I don't know what it's complaining about there, and I don't have any experience with CMake or the time to learn it. (Someone else contributed the CMake support).

Perhaps the literal brackets need to be double-escaped in that regex string as \\[ and \\] in the CMakeLists.txt file.

**Comment by MKrbm** [comment]
You are right!. Now works fine. Thank you.
