### ISSUE TITLE
Failed build when trying to make static library (mingw)

### ISSUE THREAD

**Issue by aullidolunar** [hyperrealm/libconfig#25]
Hi, I'm trying to build a static library with mingw (4.9.2) on windows with msys. I open msys env. with this build command line:

$ ./configure --prefix=c:/usr CFLAGS="-static -static-libgcc -static-libstdc++" CXXFLAGS="-static -static libgcc -static-libstdc++" LIBS="-lpthread" --disable-examples

These are the errors:
libconfig_tests-tests.o:tests.c:(.text+0x47): undefined reference to `_imp__config_init'
libconfig_tests-tests.o:tests.c:(.text+0x5c): undefined reference to `_imp__config_set_include_dir'
libconfig_tests-tests.o:tests.c:(.text+0x70): undefined reference to `_imp__config_read_file'
libconfig_tests-tests.o:tests.c:(.text+0xe7): undefined reference to `_imp__config_write_file'
libconfig_tests-tests.o:tests.c:(.text+0x1ef): undefined reference to `_imp__config_destroy'
libconfig_tests-tests.o:tests.c:(.text+0x207): undefined reference to `_imp__config_init'
libconfig_tests-tests.o:tests.c:(.text+0x21b): undefined reference to `_imp__config_read_file'
libconfig_tests-tests.o:tests.c:(.text+0x2b7): undefined reference to `_imp__config_destroy'
libconfig_tests-tests.o:tests.c:(.text+0x393): undefined reference to `_imp__config_init'
libconfig_tests-tests.o:tests.c:(.text+0x3a7): undefined reference to `_imp__config_read_string'
libconfig_tests-tests.o:tests.c:(.text+0x43c): undefined reference to `_imp__config_destroy'

any help?

**Comment by tpoechtrager** [comment]
Try

    ./configure --enable-static --disable-shard
    cd lib
    make && make install

**Comment by aullidolunar** [comment]
Thanks, that helped :)

**Comment by hyperrealm** [comment]
This is probably due to the incorrect linker path in the tests/Makefile.am, which was fixed.
