### ISSUE TITLE
Tests fail to build when building with a prefix

### ISSUE THREAD

**Issue by banks** [hyperrealm/libconfig#26]
Background: we have a build system based on Boost Build in a C++ code base. We have custom commands that allow building autotools targets within boost build such that we can just add them as dependencies for other projects. It works well in general, but does rely on the thirdparty projects being able to build successfully with `./configure --prefix=<absolute path to location in build system dir>`.

libconfig builds the library just fine but fails to build the tests due to this line: https://github.com/hyperrealm/libconfig/blob/master/tests/Makefile.am#L8

If I change `-I../lib` to `-I$(top_srcdir)/lib`, it works fine. Seems that is an oversight.

I can make a pull request if you like but I suspect it's as quick for you to make the change directly unless I've missed some reason that would be problematic.

Thanks for the great lib.

**Comment by hyperrealm** [comment]
Thanks Paul, that is indeed an oversight. I'll patch it.
