### ISSUE TITLE
Addition of an iterator for going through a list or array of Settings.

### ISSUE THREAD

**Issue by m-renaud** [hyperrealm/libconfig#3]
Instead of having to loop through a list or array of `Setting`s by index, it would be convenient if there was an iterator class defined as well as a `begin()` and `end()` method for the `Setting` class, obviously only valid if the setting represents a container type. For example, from `example1.cpp`:

    const Setting &books = root["inventory"]["books"];
    int count = books.getLength();
    for(int i = 0; i < count; ++i)
    {
      const Setting &book = books[i];
      // Do stuff with book.
    }

could be replaced with:

    const Setting &books = root["inventory"]["books"];
    for (Setting const& book : books)
        // Do stuff with book.

**Comment by hyperrealm** [comment]
This feature was merged.
