### ISSUE TITLE
minor/documentation

### ISSUE THREAD

**Issue by chalaev** [hyperrealm/libconfig#30]
I suggest changing one line in libconfig documentation:
"Function: config_setting_t * config_root_setting (const config_t * config)
    This function returns the root setting for the configuration config. "
into 
"Function: config_setting_t * config_root_setting (const config_t * config)
    This function, which is implemented as a macro,  returns the root setting for the configuration config. "

**Comment by hyperrealm** [comment]
Have made a patch for that. Thanks.
