### ISSUE TITLE
improve to CONFIG_FORMAT

### ISSUE THREAD

**Issue by zhaopingsun** [hyperrealm/libconfig#31]
current config format is not so friendly ,for example  when I try to write 1.57 using program, it will write something like 1.569876，so I plan to add printf  like interface to libconfig,
such as 
```
config_setting_t *pcs=config_settting_add(*flt,"pw",CONFIG_TYPE_FLOAT);
config_set_print_format("%.2f");
```

Will you accept that feature?

**Comment by hyperrealm** [comment]
Sounds reasonable, but how about with a simpler API like:

config_set_float_precision(int decimals)

Then caller doesn't have to pass a printf format string and we don't have to try to validate it.

**Comment by zhaopingsun** [comment]
It's a compromise between flexible and robust,we do not need the flexibility of general programming language in this project , the API like config_set_float_precision(int decimals)  is good enough for most of the users, I will try to summit the patch later.

**Comment by jltallon** [comment]
config_set_digits(config_t *config, unsigned short digits)

**Comment by jltallon** [comment]
@hyperrealm : this is a potentially incompatible change.
a) change the precision, keep "%.*g" specifier --- digits => maximum significant digits
