### ISSUE TITLE
How to build library using windows?

### ISSUE THREAD

**Issue by Rene107** [hyperrealm/libconfig#33]
I want to use libconfig in my project, but I don't know how to build this library. 
I use Qt Creator on Windows with Cmake for my projects.

Currently I've added the following code to my CMakeList.txt :

set(CONFIG "${SRCROOT}/libconfig/lib/grammar.c"
           "${SRCROOT}/libconfig/lib/libconfig.c"
           "${SRCROOT}/libconfig/lib/libconfigcpp.c++"
           "${SRCROOT}/libconfig/lib/scanctx.c"
           "${SRCROOT}/libconfig/lib/scanner.c"
           "${SRCROOT}/libconfig/lib/strbuf.c")
add_library(libconfig STATIC ${CONFIG})
SET_TARGET_PROPERTIES(libconfig PROPERTIES LINKER_LANGUAGE C)
setup_library_target(libconfig "${CODEROOT}/lib")

add_executable(TV_1_Validate_ODE_Solver "${SRCROOT}/TV_1_Validate_ODE_Solver.cpp")
setup_executable_target(TV_1_Validate_ODE_Solver "${SRCROOT}")
target_link_libraries(TV_1_Validate_ODE_Solver
                                        tudat_numerical_integrators
                                        libconfig
                                        ${TUDAT_CORE_LIBRARIES}
                                        ${Eigen_LIBRARIES}
                                        ${Boost_LIBRARIES})

I start my executable source file with:
#include "libconfig/lib/libconfig.h++"

The CMake File runs, but I get an error when building the executable. I get the following error:
\TV_1_Validate_ODE_Solver.cpp:162: error: undefined reference to `_imp___ZN9libconfig6ConfigC1Ev'

While I only construct cfg on that line:
Line 162: libconfig::Config cfg;

I get similar errors on the lines:
cfg.readFile("TV_1_Config.cfg");
catch(const libconfig::ParseException &pex)

In addition, I get the following error:
collect2.exe:-1: error: error: ld returned 1 exit status

Any Idea on how to fix this?

**Comment by hyperrealm** [comment]
I really don't have any knowledge of CMake. Wouldn't it be simpler to just build & install libconfig using the configure script and then point your CMake file at the binaries and headers?

**Comment by Rene107** [comment]
That seems indeed simpler to me, but I tried running the configure script using CMD and it didnt work. So how do I run the script then?

**Comment by hyperrealm** [comment]
That depends on which toolchain you're using to build your project. If you're using the GNU toolchain then you'd need to install MinGW environment and run configure inside the shell that comes with MinGW.  If you're using the Visual C++ compiler then you can build the library using Visual Studio Express and copy the .dll, .lib, and .h files to an installation directory of your choice.
