### ISSUE TITLE
ambiguous config_setting_get_int() return value

### ISSUE THREAD

**Issue by bernardgut** [hyperrealm/libconfig#38]
Hi
First: thanks for your work.

So I parse a configuration file with a key that can either be a scalar
```
somekey=X
```

or a table of scalar values:
```
somekey=[X,Y.Z]
```

The following compiles and work properly, for X,Y,Z strings:
```C
static int parse_devices(void)
{
        const config_setting_t *devs=NULL;
        const char *dev=NULL;
        int i, ret;

        devs=config_lookup(&cfg, "devices");
        if(!devs){
                return -EINVAL;
        }
        dev=config_setting_get_string(devs);
        if(dev){
                return add_dev(dev);
        }
        for(i=0;i<config_setting_length(devs);++i){
                dev=NULL;
                dev=config_setting_get_string_elem(devs, i);
                ret=add_dev(dev);
                if(ret){
                        return ret;
                }
        }
        return 0;
}
```

Now while the above provides the desired functionality, the following will compile but not work as intended :
```C
static int parse_nodes(void)
{
        int i, ret, node;
        config_setting_t *nodes=NULL;

        nodes=config_lookup(&cfg, "nodes");
        if(!nodes){
                return -EINVAL;
        }
        node=config_setting_get_int(nodes);
        if(node){
                return add_node(node);
        }
        for(i=0;i<config_setting_length(nodes);++i){
                node=config_setting_get_int_elem(nodes, i);
                ret=add_node(node);
                if(ret){
                        return ret;
                }
        }
        return 0;
}
```

The problem is that there is no way of knowing if `config_setting_get_int` succeeded or not, because any error code returned can also be a valid number that was parsed. How can I implement the same functionality as defined in the first code snippet for int/int64 types in a somewhat proper way ? 

Or am I missing something?

thanks
- Bernard

**Comment by hyperrealm** [comment]
config_setting_lookup_int() is the function you want; it stores the int value in a value-result parameter and returns the error code as its return value, so there's no ambiguity.
