### ISSUE TITLE
Unification of interface for looking up a setting from Config and Setting object.

### ISSUE THREAD

**Issue by m-renaud** [hyperrealm/libconfig#4]
Currently, to lookup a setting from a `Config` object, one must use the `lookup()` method, but for looking up a setting from a `Setting` object, one must use `operator[]`. It would make more sense if both classes implemented both ways of looking up settings so the interface is consistent between them.

The modification would be quite simple as each class could delegate the call to the method that is already implemented, or to keep the code clean, move the implementation to the `lookup()` method in both classes and then have `operator[]` invoke `lookup()`.

**Comment by hyperrealm** [comment]
Setting has lookup() now.

I prefer not to change the behavior of operator[]. It's behaving the way it does for regular arrays in C/C++, dictionaries in Objective-C and Python, etc..

Closing this as resolved.
