### ISSUE TITLE
Removing a libconfig::Setting removes sibling

### ISSUE THREAD

**Issue by random85** [hyperrealm/libconfig#41]
I'm trying to overwrite a setting that can be from another type of the original. To do that, I first try to remove the existing and add a new one using the new type. However, when I remove a setting, all the siblings are removed as well.

This small test program:
```cpp
#include <string>
#include <iostream>

#include <libconfig.h++>

int main(int argc, char* argv[])
{
	std::string szConfig  = "a:{b:3;c:4;}";
	libconfig::Config libConfig;
	
	try
	{
		libConfig.readString(szConfig);
		libConfig.getRoot().remove("a.b");
		libConfig.writeFile("/tmp/testconfig.cfg");
		libConfig.lookup("a.c");  //<--- SettingNotFoundException
	}
	catch(std::exception const& ex)
	{
		std::cerr << ex.what() << std::endl;
		return -1;
	}
	
	return 0;
}
```

Gives me the following output:
```
SettingNotFoundException
```

Is that an expected behavior? IMHO, no, if I trust the documentation "a.b" is not a group and a SettingTypeException shall be thrown... But that is not the case! The created file is empty!

**Comment by hyperrealm** [comment]
There is no "ab" or "ac". You can reference "a.b" or "a.c", but remove does not support paths. My guess is the exception is being thrown by the remove call, not the lookup call.

**Comment by random85** [comment]
When I take time to try to narrow down the problem and post a clear message, I appreciate when it is read carefully...
* The created file is empty!
* Where am I talking about "ab" or "ac"?

>but remove does not support paths

Good to know! What's the reason behind this? I need that feature, how much work would it be?

I'm a little confused because it doesn't behave like documented, the code or the documentation should be fixed. If you give me some indications, I would be glad to help.

**Comment by jltallon** [comment]
Applied patch and tested it.
The supplied test program finishes successfully and creates the following output:
   a : { c = 4; };
(as expected).

Thank you

**Comment by random85** [comment]
Thanks for considering my patch, happy to see my name in the release notes! I was just wondering if there was a more efficient way to do it.
