### ISSUE TITLE
removing scanner.c and scanner.h

### ISSUE THREAD

**Issue by chaxgit** [hyperrealm/libconfig#48]
HI this is more of a clarification request - than an issue.
Please do indulge me as I didn't find an IRC channel.

I'm trying to change some grammar rules in scanner.l and grammar.y - and try to regenerate grammar.[ch] and scanner.[ch]  (added new tokens and such.)
While grammar.[ch] - get generated during a make - the scanner.c doesn't. And I'm unable to figure how to re-generate scanner code. Can anyone please help me ?

**Comment by chaxgit** [comment]
--- libconfig-1.4.9_2/libconfig-1.4.9/lib/scanner.l	2012-09-28 21:17:18.000000000 -0700
+++ libconfig-1.4.9/lib/scanner.l	2016-01-06 15:25:56.000000000 -0800
@@ -92,6 +92,7 @@
 hex64             0[Xx][0-9A-Fa-f]+L(L)?
 hexchar           \\[Xx][0-9A-Fa-f]{2}
 float             ([-+]?([0-9]*)?\.[0-9]*([eE][-+]?[0-9]+)?)|([-+]?([0-9]+)(\.[0-9]*)?[eE][-+]?[0-9]+)
+nameval           [A-Za-z0-9\.\*][-A-Za-z0-9_\.\*]*
 comment           (#|\/\/).*$
 include_open      ^[ \t]*@include[ \t]+\"
 
@@ -163,6 +164,7 @@
 {false}           { yylval->ival = 0; return(TOK_BOOLEAN); }
 {name}            { yylval->sval = yytext; return(TOK_NAME); }
 {float}           { yylval->fval = atof(yytext); return(TOK_FLOAT); }
+{nameval}         { yylval->sval = yytext; return(TOK_NAMEVAL); }
 {integer}         { yylval->ival = atoi(yytext); return(TOK_INTEGER); }
 {integer64}       { yylval->llval = atoll(yytext); return(TOK_INTEGER64); }

--- libconfig-1.4.9_2/libconfig-1.4.9/lib/grammar.y	2011-06-25 03:40:32.000000000 -0700
+++ libconfig-1.4.9/lib/grammar.y	2016-01-06 15:26:03.000000000 -0800
@@ -92,7 +92,7 @@
 %token <ival> TOK_BOOLEAN TOK_INTEGER TOK_HEX
 %token <llval> TOK_INTEGER64 TOK_HEX64
 %token <fval> TOK_FLOAT
-%token <sval> TOK_STRING TOK_NAME
+%token <sval> TOK_STRING TOK_NAME TOK_NAMEVAL
 %token TOK_EQUALS TOK_NEWLINE TOK_ARRAY_START TOK_ARRAY_END TOK_LIST_START TOK_LIST_END TOK_COMMA TOK_GROUP_START TOK_GROUP_END TOK_SEMICOLON TOK_GARBAGE TOK_ERROR
 
 %%
@@ -347,6 +347,12 @@
       _delete(s);
     }
   }
+  | TOK_NAMEVAL
+  {
+     const char *s = parsectx_take_string(ctx);
+     config_setting_set_string(ctx->setting, s);
+     _delete(s);
+  }
   ;

**Comment by chaxgit** [comment]
The above are the two changes I made and when I let it build - it builds grammar.c and grammar,h fine. But somehow scanner.h doesn't get touched (I checked timestamps based on Mark's suggestion) .

Also I get this error:

In file included from libconfig.c:28:
grammar.h:126:46: warning: declaration of 'struct parse_context' will not be visible outside of this function [-Wvisibility]
int libconfig_yyparse (void *scanner, struct parse_context *ctx, struct scan_context *scan_ctx);
                                             ^
grammar.h:126:73: warning: declaration of 'struct scan_context' will not be visible outside of this function [-Wvisibility]
int libconfig_yyparse (void *scanner, struct parse_context *ctx, struct scan_context *scan_ctx);
                                                                        ^
In file included from scanner.l:43:
grammar.h:126:46: warning: declaration of 'struct parse_context' will not be visible outside of this function [-Wvisibility]
int libconfig_yyparse (void *scanner, struct parse_context *ctx, struct scan_context *scan_ctx);
                                             ^
grammar.h:126:73: warning: declaration of 'struct scan_context' will not be visible outside of this function [-Wvisibility]
int libconfig_yyparse (void *scanner, struct parse_context *ctx, struct scan_context *scan_ctx);
                                                                        ^
libconfig.c:73:12: error: conflicting types for 'libconfig_yyparse'
extern int libconfig_yyparse(void *scanner, struct parse_context *ctx,
           ^
grammar.h:126:5: note: previous declaration is here
int libconfig_yyparse (void *scanner, struct parse_context *ctx, struct scan_context *scan_ctx);
    ^
libconfig.c:592:34: warning: incompatible pointer types passing 'struct parse_context *' to parameter of type 'struct parse_context *'
      [-Wincompatible-pointer-types]
  r = libconfig_yyparse(scanner, &parse_ctx, &scan_ctx);
                                 ^~~~~~~~~~
grammar.h:126:61: note: passing argument to parameter 'ctx' here
int libconfig_yyparse (void *scanner, struct parse_context *ctx, struct scan_context *scan_ctx);
                                                            ^
libconfig.c:592:46: warning: incompatible pointer types passing 'struct scan_context *' to parameter of type 'struct scan_context *'
      [-Wincompatible-pointer-types]
  r = libconfig_yyparse(scanner, &parse_ctx, &scan_ctx);
                                             ^~~~~~~~~
grammar.h:126:87: note: passing argument to parameter 'scan_ctx' here
int libconfig_yyparse (void *scanner, struct parse_context *ctx, struct scan_context *scan_ctx);
                                                                                      ^
scanner.c:1809:40: warning: implicit declaration of function 'isatty' is invalid in C99 [-Wimplicit-function-declaration]
        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
                                       ^

**Comment by chaxgit** [comment]
It looks like using bison 2.7 is not a good idea.

**Comment by hyperrealm** [comment]
I really have no idea what's going on with your setup.... I removed scanner.h and scanner.c, then touched scanner.l, and ran make, and it regenerated scanner.h and scanner.c without a problem. I have bison 3.0.2 and flex 2.5.39.
