### ISSUE TITLE
LIBCONFIG_VER_MINOR not updated for release 1.6

### ISSUE THREAD

**Issue by pumaking** [hyperrealm/libconfig#49]
In the latest version and release 1.6, LIBCONFIG{XX}_VER_MINOR is still defined to 5, making it difficult to check for an installed version.

For example, release 1.5 throws a linker error when the following code is compiled:

```
#include <string>
#include <libconfig.h++>
int main() {
  std::string s = libconfig::Config().lookup("");
  return 0;
}
```

```
undefined reference to `libconfig::Setting::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >[abi:cxx11]() const'
```

This is with GCC 5.2.1. The same links fine with libconfig 1.6.

**Comment by jmccrohan** [comment]
Any update on this?

Regards,
Jon

**Comment by hyperrealm** [comment]
I've updated this for 1.7 which will be coming out soon.
