### ISSUE TITLE
Change all functions in the C++ wrapper to take std::string instead of const char*.

### ISSUE THREAD

**Issue by mrenaud92** [hyperrealm/libconfig#5]
Currently, all of the functions for the C++ wrapper take `const char*` which causes a compiler error whenever you pass a `std::string` which means that `.c_str()` must be called on any string passed to one of these functions. By changing all functions to take a `std::string` and then calling `.c_str()` internally when passing the string to the C API, it would make the usage of the library much cleaner.

**Comment by omor1** [comment]
This is a more serious problem. The current documentation at http://www.hyperrealm.com/libconfig/libconfig_manual.html#The-C_002b_002b-API says that there is `Setting & operator[] (const std::string &name)` method, but this simply *does not exist!*

**Comment by hyperrealm** [comment]
Fixed.
