### ISSUE TITLE
Cannot compile with arm-linux-gnueabi

### ISSUE THREAD

**Issue by Phunkafizer** [hyperrealm/libconfig#54]
trying

./configure --host=arm-linux-gnueabi --with-sysroot=/usr/arm-linux/gnueabi
then

make

results in

make[2]: Entering directory '/home/osboxes/libconfig/lib'
  YACC     grammar.c
byacc: e - line 24 of "/home/osboxes/libconfig/lib/grammar.y", syntax error
%defines
^

**Comment by jltallon** [comment]
This is odd. Maybe a very old/incompatible yacc?? -- libconfig is developed&tested with bison mostly.
Would need some more info on this to be able to fix it.

**Comment by Phunkafizer** [comment]
it's lubuntu 4.2.0-25-generic (latest one from osboxes.org)
yacc --version
bison (GNU Bison) 3.0.2

**Comment by jltallon** [comment]
Will check and get back to you

**Comment by Phunkafizer** [comment]
Going in deep and reading lots of google results, here is how it works now:

First I had to uninstall byacc (apt-get remove byacc). Then
```
touch configure.ac aclocal.m4 configure Makefile.am Makefile.in
rm lib/scanner.c lib/scanner.h
./configure --host=arm-linux-gnueabi --prefix=/usr/arm-linux-gnueabi
sudo make install
```
And I'm able to use the lib with my crosscompiler. Maybe you can add it to the read me how to install the lib for the arm--linux-gnueabi cross...

**Comment by jltallon** [comment]
Ok. Noted.
Thank you for digging this up.
