### ISSUE TITLE
Static linking error

### ISSUE THREAD

**Issue by ratovarius** [hyperrealm/libconfig#55]
Hi,
I'm trying to link an application in c++ using libconfig.

When I try to do it static,

g++ -Wl,-subsystem,console -mthreads -o debug\Sim.exe object_script.Sim.Debug  C:/MinGW/msys/1.0/local/lib/libconfig++.a

i get,

./debug\Confi.o: In function `ZN12ConfiguradorC2EP9Sim':
./Confi.cpp:8: undefined reference to`_imp___ZN9libconfig6ConfigC1Ev'

And when I do it with the shared library,

g++ -Wl,-subsystem,console -mthreads -o debug\Sim.exe object_script.Sim.Debug  C:/MinGW/msys/1.0/local/lib/libconfig++.dll.a

It links without errors.

Any help?

**Comment by hyperrealm** [comment]
You need to '#define LIBCONFIG_STATIC' in your code before you #include the libconfig header(s), otherwise the wrong export attributes will be generated.
