### ISSUE TITLE
Feature request: include directives enhancement

### ISSUE THREAD

**Issue by raulot-a** [hyperrealm/libconfig#57]
Hi. Actually if we doesn't specify an absolute path for the include directive, it loads included configuration file from the path where the binary which loads the main configuration file is executed.
In some cases, I think it would be useful to be able to load included configuration files from the place where the main configuration file is without specifying the absolute path.

**Comment by jltallon** [comment]
This feature works as documented:
 - With an absolute path [begins with "/" or "\" as appropriate), it reads the file (or directory) at that location
 - Without an absolute path, the file is searched for at $CWD (current working directory) or the directory specified as "include base dir" parameter to the library.

**Comment by raulot-a** [comment]
It was not exactly what I expected but it has solved my problem. My bad and thank you again.
