### ISSUE TITLE
Build error on Mingw_w64

### ISSUE THREAD

**Issue by tjadevries** [hyperrealm/libconfig#60]
As suggested elsewhere (issue #47) I have removed `scanner.c` and `scanner.h` (otherwise I get the error mentioned there).
If I then compile, I get this error:
`scanner.l:187:63: error: 'alphasort' undeclared (first use in this function)
         if(scanctx_dirscan(yyextra, basedir, filter_dotfiles, alphasort) < 0)`

Don't know how to fix...

**Comment by jltallon** [comment]
Yup. Pending release of 1.6.1, which will update that file.
Upon a "developer rebuild" the file gets regenerated... so just delete it and rebuild.
