### ISSUE TITLE
There's inconsistency in Makefile.in and Makefile.am about VERINFO

### ISSUE THREAD

**Issue by pyhalov** [hyperrealm/libconfig#61]
We have in libconfig-1.6/lib/Makefile.am:
VERINFO = -version-info 11:1:3 (leading to libconfig++.so.8.3.1)
and in libconfig-1.6/lib/Makefile.in:
VERINFO = -version-info 11:0:2 (leading to libconfig.so.9.2.0)

**Comment by hyperrealm** [comment]
This is fixed now.

Removing the .in files would work, but it then makes it harder to build the package without having all the autotools installed. (You can't just run ./configure)
