### ISSUE TITLE
libconfig 1.5 not compiling - Windows 10, Visual Studio 2013

### ISSUE THREAD

**Issue by prechtl** [hyperrealm/libconfig#65]
Since Version 1.7 won't build due to it's use of dirent.h, I tried to download the v1.5 tarball and build that in Visual Studio.  The build is failing with the error:
`libconfig.obj : error LNK2019: unresolved external symbol S_ISDIR referenced in function config_read_file`

Apparently S_ISDIR is a posix macros and does not work on Windows.  Is there libconfig source that will build on Windows?

**Comment by hyperrealm** [comment]
I'll fix that ASAP. In the meantime you can just add these lines to 'wincompat.h', after the first #if in that file.

#if !defined(S_ISDIR) && defined(S_IFMT) && defined(S_IFDIR)
#define S_ISDIR(m) (((m) & S_IFMT) == S_IFDIR)
#endif

**Comment by prechtl** [comment]
Thanks - that worked.

(I just had to adjust one other line in example1.cpp, changing line 58 to read: 
`string name = cfg.lookup("name").c_str();`
And then everything in libconfig compiled)
