### ISSUE TITLE
scanner.c and scanner.h need to be regenerated or removed from source control

### ISSUE THREAD

**Issue by ilovezfs** [hyperrealm/libconfig#66]
I can workaround the build failure below by touching `lib/scanner.l` or just deleting `lib/scanner.c`, which implies that those generated files need to be regenerated to prevent build failures. Also, there's a parallelization bug. If I run `cd lib ; make maintainer-clean-generic ; make` it will fail unless I instead do `cd lib ; make maintainer-clean-generic ; make -j1`.

```
==> make install
Making install in lib
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-am
  CC       libconfig_la-libconfig.lo
  CC       libconfig_la-scanner.lo
  CC       libconfig_la-grammar.lo
  CC       libconfig_la-scanctx.lo
  CC       libconfig_la-strbuf.lo
  CC       libconfig___la-libconfig.lo
  CC       libconfig___la-scanner.lo
  CC       libconfig___la-grammar.lo
  CC       libconfig___la-scanctx.lo
  CC       libconfig___la-strbuf.lo
  CXX      libconfig___la-libconfigcpp.lo
scanner.l:137:59: error: too few arguments to function call, expected 4, have 3
                                                    &error);
                                                          ^
./scanctx.h:66:1: note: 'scanctx_push_include' declared here
extern FILE *scanctx_push_include(struct scan_context *ctx, void *prev_buffer,
^
scanner.l:137:59: error: too few arguments to function call, expected 4, have 3
                                                    &error);
                                                          ^
./scanctx.h:66:1: note: 'scanctx_push_include' declared here
extern FILE *scanctx_push_include(struct scan_context *ctx, void *prev_buffer,
^
1 error generated.
1 error generated.
make[2]: *** [libconfig_la-scanner.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [libconfig___la-scanner.lo] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make install
```

**Comment by ilovezfs** [comment]
I believe this is a duplicate of https://github.com/hyperrealm/libconfig/issues/53 and https://github.com/hyperrealm/libconfig/issues/64 but figured it would be best to create a separate issue identifying the problem.

**Comment by ilovezfs** [comment]
Here's the corresponding Homebrew pull request: https://github.com/Homebrew/homebrew-core/pull/1752

**Comment by jltallon** [comment]
On 06/06/2016 06:26 PM, ilovezfs wrote:
>
> Here's the corresponding Homebrew pull request: 
> Homebrew/homebrew-core#1752 
> <https://github.com/Homebrew/homebrew-core/pull/1752>
>

Don't worry. This will be fixed in 1.6.1, coming soonish
  (at least, I should be able to devote time to this in two weeks' time)

**Comment by shehzadkhawar** [comment]
long time. Still happens with my system when running make

Linux ubuntu 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

  CC       libconfig_la-libconfig.lo
  CC       libconfig_la-scanner.lo
scanner.l: In function 'libconfig_yylex':
scanner.l:137:53: warning: passing argument 3 of 'scanctx_push_include' from incompatible pointer type [enabled by default]
                     char c[2] = { (char)(strtol(yytext + 2, NULL, 16) & 0xFF),
                                                     ^
In file included from scanner.l:46:0:
scanctx.h:66:14: note: expected 'const char *' but argument is of type 'const char **'
 extern FILE *scanctx_push_include(struct scan_context *ctx, void *prev_buffer,
              ^
scanner.l:137:53: error: too few arguments to function 'scanctx_push_include'
                     char c[2] = { (char)(strtol(yytext + 2, NULL, 16) & 0xFF),
                                                     ^
In file included from scanner.l:46:0:
scanctx.h:66:14: note: declared here
 extern FILE *scanctx_push_include(struct scan_context *ctx, void *prev_buffer,
              ^
make[3]: *** [libconfig_la-scanner.lo] Error 1
make[3]: Leaving directory `/home/khawarshehzad/repos/libconfig/lib'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/khawarshehzad/repos/libconfig/lib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/khawarshehzad/repos/libconfig'
make: *** [all] Error 2

**Comment by stv0g** [comment]
Yes, please lets remove all the generated files from git.

This also applies to the auto{conf,make} stuff.

**Comment by hyperrealm** [comment]
Removed.
