### ISSUE TITLE
documentation: add "supported platforms" section

### ISSUE THREAD

**Issue by chalaev** [hyperrealm/libconfig#67]
One strong side of libconfig is its universality: apart from C and C++ it is available in perl, python, and perhaps in some other programming languages. Using libconfig, C++ programs can exchange data with perl, for example.
I recently finished writing [common lisp interface for libconfig](https://github.com/chalaev/cl-libconfig); may be you could mention it in a newly created section "Supported platforms" somewhere in the documentation.

**Comment by hyperrealm** [comment]
Addressed in 7ef44826bc33f975102c20a4be2b5f2ab0b0f38a
