### ISSUE TITLE
cannot find config++.lib

### ISSUE THREAD

**Issue by RichieZh** [hyperrealm/libconfig#68]
Hi

I am re-runing a project which uses Config++ 1.4.7 and the code ownner give your url: www.hyperrealm.com/libconfig/

And I only find libconfig here and I tried to use the libconfig 1.5.

The code includes libconfig.h++. But I got this error: "error LINK 1104, can not open 'config++.lib'".

Is config++.lib is part of your library? 

Thanks
Richie

**Comment by hyperrealm** [comment]
Are you using MinGW to build it, or Visual Studio?

Visual Studio produces a libconfig++.lib, not a config++.lib. Probably you forgot to add the library to the linker dependencies?

**Comment by hyperrealm** [comment]
Verified that Visual Studio (2017) produces correct libconfig++.lib and libconfig++.dll, so closing this as not reproducible.
