### ISSUE TITLE
[Q] Outdated on CentOS 6

### ISSUE THREAD

**Issue by dterweij** [hyperrealm/libconfig#74]
CentOS 6 uses version 1.3.2 in the base and seems no updates to it. So thats why I found out the examples that I found here did not work/compile.  Do you maintain that CentOS 6 Package? please update it.
I hope I can use this, hardcoding things is not right :)
Thank you for the lib. I hope to recreate my Windows (Visual Basic) tool in Linux. Using GTK2/C/Eclipse.  Tho "Visual" coding on Linux sucks a bit :) I dont like Glade, why is it all in boxes.. why not drag a element on the window where I want it :-) anyway different story. Again thanx for the lib. I go try to make a own rpm package with libconfig current version and hope it works :) Until then, hardcoded val's.

**Comment by hyperrealm** [comment]
Sorry I don't maintain CentOS package or have access to a CentOS system. What packaging system does it use?

I strongly recommend using Qt (the toolkit, and the Creator IDE) to build GUI apps on Linux. That GTK+/Glade stuff is stone-age by comparison.

**Comment by VIKLO11** [comment]
Excuse me Danny I want if you could help me in giving me some code to install kloxo 6.1 without installation file you know that it depends on lxcenter.org which is dead so please brother do give me a hand so I can install kloxo 6.1.x and I can overcome yum gave errors ,you forgot to leave a guide to install kloxo on 2017:-)
Yes brother Danny please help the world to install kloxo on 2017,YES 32 BIT KLOXO on 2017 ,its impossible with the installation files as they come,please give us some codes to install it without those lxcenter https that just boicot everything,I f you can help it will be sore truly appreciated and thand thanked full overly

**Comment by hyperrealm** [comment]
Closing as not feasible...I don't have access to CentOS nor the cycles available to be a binary package maintainer.
