### ISSUE TITLE
Unable to access libconfig documentation

### ISSUE THREAD

**Issue by tomer** [hyperrealm/libconfig#80]
I am using an application which use libconfig and links to the [libconfig documentation] from its own documentation. Unfortunately, the hyperrealm.com website is down for at least a week (according to Google cache), so the links become invalid and points to HTTP 500 error. 

[libconfig documentation]: http://www.hyperrealm.com/libconfig/libconfig_manual.html

**Comment by hyperrealm** [comment]
My web hosting company got greedy so I had to switch to a new one. Still rebuilding the website...it will take time.

You can always generate your own documentation with 'make html' and 'make pdf'.

**Comment by tomer** [comment]
I'd suggest using [GitHub Pages] as a location for documentation. This way you can bundle the whole documentation directly with the code repository. 

[GitHub Pages]: https://pages.github.com/

**Comment by hyperrealm** [comment]
Good idea, I'll do that. Thanks.

**Comment by hyperrealm** [comment]
GitHub page is now live at https://hyperrealm.github.io/libconfig/
