### ISSUE TITLE
v.1.6.tar.gz compilation error on centos7

### ISSUE THREAD

**Issue by Peter-YAN** [hyperrealm/libconfig#82]
After  ./configure && make, the following error i got.

_In file included from scanner.l:46:0:
scanctx.h:66:14: note: expected 'const char *' but argument is of type 'const char **'
 extern FILE *scanctx_push_include(struct scan_context *ctx, void *prev_buffer,
              ^
scanner.l:137:53: error: too few arguments to function 'scanctx_push_include'
                     char c[2] = { (char)(strtol(yytext + 2, NULL, 16) & 0xFF),
                                                     ^
In file included from scanner.l:46:0:_

then , i change include statement of scanner.l, the problem is solved.

**FROM** 
_#include <stdlib.h>
#include <errno.h>
#include <ctype.h>
#include <string.h>
#include <limits.h>
#include <dirent.h>  
#include "parsectx.h"                                
**#include "scanctx.h"**
#include "grammar.h"
#include "wincompat.h"_

**TO**

_**#include "scanctx.h"**
#include <stdlib.h>
#include <errno.h>
#include <ctype.h>
#include <string.h>
#include <limits.h>
#include <dirent.h>  
#include "parsectx.h"
#include "grammar.h"
#include "wincompat.h"_

**Comment by wjz2047** [comment]
it helps

**Comment by hyperrealm** [comment]
Generated files have been removed from repo.
