### ISSUE TITLE
new build method / install docu

### ISSUE THREAD

**Issue by Phunkafizer** [hyperrealm/libconfig#86]
In the INSTALL file it is described to run ./configure, but this does not exist anymore.
So I tried  (on Linux Ubuntu):

sudo autoconf configure.ac

But this throws some errors:
configure.ac:8: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:9: error: possibly undefined macro: AM_CONFIG_HEADER
configure.ac:25: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:27: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
configure.ac:28: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:30: error: possibly undefined macro: AM_PROG_LEX
configure.ac:100: error: possibly undefined macro: AM_CONDITIONAL

**Comment by hyperrealm** [comment]
Running ‘autoreconf’ should regenerate everything

**Comment by hyperrealm** [comment]
INSTALL file was updated in 3443d680bb983231ac5c158df444f36ae4b45637
